### ISSUE TITLE
Hard coded path inside 'PostBuildEvent'

### ISSUE THREAD

**Issue by LaurentDardenne** [jhoek/UncommonSense.PowerShell.TypeData#1]
This [file](https://github.com/jhoek/UncommonSense.PowerShell.TypeData/blob/master/UncommonSense.PowerShell.TypeData/UncommonSense.PowerShell.TypeData.csproj) contains hard coded path : 
```xml
    <PostBuildEvent>md c:\users\jhoek\Documents\WindowsPowerShell\Modules\UncommonSense.PowerShell.TypeData\
copy $(TargetDir)System.Management.Automation.dll c:\users\jhoek\Documents\WindowsPowerShell\Modules\UncommonSense.PowerShell.TypeData\
copy $(TargetDir)UncommonSense.PowerShell.TypeData* c:\users\jhoek\Documents\WindowsPowerShell\Modules\UncommonSense.PowerShell.TypeData\</PostBuildEvent>
</PropertyGroup>
```
Note : the automation.dll is a powershell runtime dll
```Powershell
> [psobject].Assembly.fullname
System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
```

**Comment by jhoek** [comment]
Thanks for reporting this - you are absolutely right. Removed the PostBuildEvent in commit 249fa19. 

Any suggestions how I should handle copying the built dll to my modules folder (for testing purposes) in a more generic way that will also work for other users? 

I'm not sure what you mean by your second remark? Did you mean there was no point in copying it to the Modules folder since it's already part of PowerShell? If so, we agree again! :-)

**Comment by LaurentDardenne** [comment]
> Any suggestions how I should handle copying the built dll to my modules folder (for testing purposes) in a more generic way that will also work for other users?


There are many ways. I use a psake script outside VS or a batch in PostBuildEvent
```
rem call "$(ProjectDir)PostBuild.bat" $(ProjectDir) $(TargetDir) $(TargetFileName)

set ProjectDir=%1
set TargetDir=%2
set TargetFileName=%3
set ModulePath=%HOMEDRIVE%%HOMEPATH%\Documents\WindowsPowerShell\Modules\Myproject
```
The ideal is to have an archive or nuget feed (Appveyor artefact) with the compiled dll, many Powershell users dont have Visual Studio.
See : https://github.com/TravisEz13/PoshBuildTools

> Did you mean there was no point in copying it to the Modules folder since it's already part of PowerShell?

Yes. We need a reference only to compile.

```powershell
Dir
    Directory: C:\Users\Laurent\Documents\WindowsPowerShell\Modules\UncommonSense.PowerShell.TypeData
    
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       11/02/2017     12:07          23040 UncommonSense.PowerShell.TypeData.dll
-a----       23/01/2017     04:43           7884 UncommonSense.PowerShell.TypeData.psd1
-a----       11/02/2017     13:58            626 UncommonSense.PowerShell.TypeData.psm1

ipmo UncommonSense.PowerShell.TypeData
[appdomain]::CurrentDomain.GetAssemblies().location
#C:\Windows\Microsoft.Net\assembly\GAC_MSIL\System.Management.Automation\v4.0_3.0.0.0__31bf3856ad364e35\System.Management.Automation.dll
#C:\Users\Laurent\Documents\WindowsPowerShell\Modules\UncommonSense.PowerShell.TypeData\UncommonSense.PowerShell.TypeData.dll
```

**Comment by jhoek** [comment]
I would like to make this as robust and low-tech as possible; it should work on my machine (as the old, obviously wrong code did) and on any user's machine _with as few assumptions about their configuration as possible_. I guess that a batch file could meet that goal, although it already seems to assume where their module folder is? 

Once the code is in a reasonable shape (and your issues are certainly helping), I think I could start by creating a release on GitHub. Don't have much experience with NuGet.

**Comment by LaurentDardenne** [comment]
>  I guess that a batch file could meet that goal, although it already seems to assume where their module folder is?

 Yes, a test on %PSModulePath% is possible.
 ```Powershell 
$Env:PSModulePath -split ';'
$UserModulePath=($Env:PSModulePath -split ';')[0]
```

For my tests i use [Myget](https://www.myget.org/gallery/ottomatt) instead [Powershell Gallery](https://www.powershellgallery.com/items).
I think to add Temporarily on my Myget repository an unofficial package, because i have  a [dependency](https://github.com/LaurentDardenne/ExtensionMethod/blob/master/src/ExtensionMethod.psd1#L57) on your module.

**Comment by LaurentDardenne** [comment]
FYI, an unofficial package is online.

```Powershell
$PSGalleryPublishUri = 'https://www.myget.org/F/ottomatt/api/v2/package'
$PSGallerySourceUri = 'https://www.myget.org/F/ottomatt/api/v2'

Register-PSRepository -Name OttoMatt -SourceLocation $PSGallerySourceUri -PublishLocation $PSGalleryPublishUri #-InstallationPolicy Trusted
Install-Module UncommonSense.PowerShell.TypeData # -Repository OttoMatt
```
I modified the module version to 1.0.1
