### ISSUE TITLE
Some elements can have an attribute named IsHidden

### ISSUE THREAD

**Issue by LaurentDardenne** [jhoek/UncommonSense.PowerShell.TypeData#10]
Some elements can have an attribute named _IsHidden_ :
```Powershell
Cd c:\temp\
@'
<?xml version="1.0" encoding="utf-8" ?>
<Types>
  <Type> 
     <Name>System.Object</Name> 
     <Members> 
        <ScriptProperty IsHidden='true'> 
         <Name>My</Name> 
         <GetScriptBlock>
           return "Test $(Get-Date)"
        </GetScriptBlock>
      </ScriptProperty>    
     </Members> 
  </Type>
</Types> 
'@> .\System.Object.types.ps1xml 
Update-TypeData -PrependPath .\System.Object.types.ps1xml
$s='Ets'
$s.My
#Test 04/12/2017 14:37:27

$s|gm -MemberType property
#   TypeName: System.String
#Name   MemberType Definition
#----   ---------- ----------
#Length Property   int Length {get;}

$s.PsObject.Properties.Name
#Length

$s.PSExtended
#psextended {MSDN}
```

Classes concerned :

> NotePropertyData 
> AliasPropertyData
> ScriptPropertyData
> CodePropertyData

> PropertySetData (to be checked)
> MemberSetData (to be checked)

**Comment by LaurentDardenne** [comment]
An example.

From C:\Windows\System32\WindowsPowerShell\v1.0\types.ps1xml :
```xml
    <Type>
        <Name>System.Management.Automation.FormatViewDefinition</Name>
        <Members>
            <CodeProperty IsHidden="true">
                <Name>InstanceId</Name>
                <GetCodeReference> 
                    <TypeName>Microsoft.PowerShell.DeserializingTypeConverter</TypeName>
                    <MethodName>GetFormatViewDefinitionInstanceId</MethodName>
                </GetCodeReference>
            </CodeProperty>
            <MemberSet>
                <Name>PSStandardMembers</Name>
                <Members>
		    <NoteProperty>
                        <Name>SerializationDepth</Name>
                        <Value>1</Value>
                    </NoteProperty>
                </Members>
              </MemberSet>
          </Members>
    </Type>
```
```Powershell
 Types {
    _Type System.Management.Automation.FormatViewDefinition {
        $getter= CodeReference Microsoft.PowerShell.DeserializingTypeConverter GetFormatViewDefinitionInstanceId
        CodeProperty InstanceId -GetCodeReference $Getter
        MemberSet PSStandardMembers {
            NoteProperty SerializationDepth 1
        }
    }
}
```

**Comment by jhoek** [comment]
I see what you mean. 

Judging from [this](https://msdn.microsoft.com/en-us/library/system.management.automation.runspaces.membersetdata(v=vs.85).aspx), MemberSetData also has it. Same for PropertySetData. 

Silly enough, I had not realised the link between these classes and the file format. Looks like we've got everything covered once we add this one property. 

I'll try to find the time tomorrow.

**Comment by LaurentDardenne** [comment]
_>>Silly enough, I had not realised the link between these classes and the file format._
I do not think, a lack of clear documentation certainly.

On [MSDN](https://msdn.microsoft.com/en-us/library/ms714674(v=vs.85).aspx) :
_For more information about ETS and how Windows PowerShell uses objects, see Windows PowerShell Object Concepts (ps) and [Windows PowerShell Extended Type System (ETS) (ps)](https://msdn.microsoft.com/en-us/library/ms714661(v=vs.85).aspx) ._

**Comment by jhoek** [comment]
Both these links appear to take me to pages that say "This Topic Is No Longer Available" - is that what you mean?

**Comment by LaurentDardenne** [comment]
_>> is that what you mean?_
Yes.

Thanks for adding.
