### ISSUE TITLE
The use of -IsHidden parameter throw an ParameterBindingException

### ISSUE THREAD

**Issue by LaurentDardenne** [jhoek/UncommonSense.PowerShell.TypeData#11]
This code throw a ParameterBindingException 

```Powershell
Types {
    _Type System.Management.Automation.FormatViewDefinition {
        $getter= CodeReference Microsoft.PowerShell.DeserializingTypeConverter GetFormatViewDefinitionInstanceId
        CodeProperty InstanceId -GetCodeReference $Getter -IsHidden 
        MemberSet PSStandardMembers {
            NoteProperty SerializationDepth 1
        }
    }
}

_Type : Missing an argument for parameter 'IsHidden'. Specify a parameter of type 'System.Nullable`1[System.Boolean]'
and try again.
At line:2 char:5
+     _Type System.Management.Automation.FormatViewDefinition {
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Type], ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,UncommonSense.PowerShell.TypeData.Cmdlets.NewTypeCmdlet
```
The IsHidden parameter must be a switch not a bool or nullable bool :
```
   -IsHidden <bool>

       Required?                    false
       Position?                    named
       Default value
       Accept pipeline input?       false
       Accep
```
And could you change the module version to 1.2.0 and the assembly version to 1.2.0.0 ?

**Comment by jhoek** [comment]
Making it a nullable bool instead of a SwitchParameter was a conscious decision, to allow three states: "true", "false" and "unspecified", since the corresponding attribute in the output file can either have value "true" or value "false", or can be absent altogether. Makes sense?

You're right about the versions - I should automate that, because I keep forgetting... :-$

**Comment by LaurentDardenne** [comment]
>>Makes sense?

Yes for developers and the possible states of this value. Or in a SGBDR context.
But I think that the default value (not specified) is considered as $false (the member is not hidden), and for Powershell using a switch ($true and $false) is sufficient.

I prefer write 
```Powershell
CodeProperty InstanceId -GetCodeReference $Getter 
```
instead
```Powershell
CodeProperty InstanceId -GetCodeReference $Getter -IsHidden:$false  # verbose
CodeProperty InstanceId -GetCodeReference $Getter -IsHidden:$null   # incomprehensible for IT !
CodeProperty InstanceId -GetCodeReference $Getter -IsHidden:$true   # redundant
```
We write what we want to do not what we do not want to do :-)

**Comment by jhoek** [comment]
@LaurentDardenne This, of course, would never be used IRL since it has no effect:
```powershell
CodeProperty InstanceId -GetCodeReference $Getter -IsHidden:$null
```

You may have convinced me. What you're proposing is the following, right?
- If `-IsHidden` is present, the attribute will appear in the output, with attribute value "true"
- If `-IsHidden` is either absent or explicitly set to `$false`, the attribute will not appear in the output.

But what about InheritMembers in MemberSet? The same thing applies there, right? 

Note to self: don't forget to bump version numbers

**Comment by LaurentDardenne** [comment]
>>What you're proposing is the following, right?

yes , wtih -IsHidden as switch parameter.

>>The same thing applies there, right?

Yes, with InheritMembers as switch parameter.
But according to [Professional Windows PowerShell Programming](http://www.wrox.com/WileyCDA/WroxTitle/Professional-Windows-PowerShell-Programming-Snapins-Cmdlets-Hosts-and-Providers.productCd-0470173939.html) : 
```
If <InheritMembers> element is present, then it must have an innerText. That innerText must be either
True or False (case-insensitive). By default, MemberSets inherit members (refer to the ‘‘PSMemberSet’’
section for more details).
```
section
```

...
InheritMemberstells this MemberSet to walk the TypeNames during a lookup of members. This
means that any members of a parent type that are in a MemberSet of the same name will be
available through this MemberSet. The default is True.

Value returns the PSMemberSet itself. An attempt to set value throws NotSupported.
...

```

May be used **-DontInheritMember** as name (inverse logic) ?

**Comment by LaurentDardenne** [comment]
Many thanks Jan :-)

**Comment by LaurentDardenne** [comment]
FYI
Mays be a bug with InheritMembers : https://github.com/PowerShell/PowerShell/issues/3578
