### ISSUE TITLE
[Request] Increase version number 

### ISSUE THREAD

**Issue by LaurentDardenne** [jhoek/UncommonSense.PowerShell.TypeData#12]
Hi,
the [last commit](https://github.com/jhoek/UncommonSense.PowerShell.TypeData/commit/c12aa6e712824d089bcf3478f21941e9643f3a34) do not change the version number of the assembly nor the version of the module.
Could you change the module version to 1.2.1 and the assembly version to 1.2.1.0 ?

**Comment by jhoek** [comment]
@LaurentDardenne Terribly sorry, should probably automate that, will take a look tonight.

**Comment by LaurentDardenne** [comment]
No problem :-)
I think that its publication on Powershell Gallery would be a good thing.

**Comment by LaurentDardenne** [comment]
Is the readme.md up to date ?
```
Aliases

The following aliases are defined automatically.
...
```

**Comment by jhoek** [comment]
@LaurentDardenne Don't have any experience with publishing to the PowerShell Gallery, but will take a look soon.

**Comment by jhoek** [comment]
@LaurentDardenne What seems to be wrong with the aliases?

**Comment by LaurentDardenne** [comment]
" _What seems to be wrong with the aliases?_"
Nothing.
My mistake, an alias command is not an alias parameter ...
Thanks for the last commit.

**Comment by jhoek** [comment]
@LaurentDardenne Took a bit longer than expected, but my module is now in the PowerShell Gallery (https://www.powershellgallery.com/packages/UncommonSense.PowerShell.TypeData/1.2.1.40). If you can, please let me know if this is what you meant. Thx!

**Comment by LaurentDardenne** [comment]
Thanks.
That's what I wanted.

For the next version maybe add some tags including this one :
```powershell
Tags = @('PSEdition_Desktop')
```

**Comment by jhoek** [comment]
Good idea. But I was also thinking that I should probably make it .NET Standard 2.0 compatible - there's nothing Windows-specific about this module's purpose or dependencies. 

Do you have any experience with upgrading binary modules from .NET Framework 4.x to .NET Standard 2.0 compatibility?

**Comment by LaurentDardenne** [comment]
_Do you have any experience with upgrading binary modules from .NET Framework 4.x to .NET Standard 2.0 compatibility?_
Not really.
