### ISSUE TITLE
Improve an error message

### ISSUE THREAD

**Issue by LaurentDardenne** [jhoek/UncommonSense.PowerShell.TypeData#2]
This code throw an exception, but I do not know where is the problem (my code or the module code) 
```powershell
Types {
   NoteProperty Baz Bar
}
Types : Impossible d'effectuer un cast d'un objet de type 'UncommonSense.PowerShell.TypeData.NoteProperty' en type
'UncommonSense.PowerShell.TypeData.Type'.
At line:1 char:1
+ Types {
+ 
    + CategoryInfo          : NotSpecified: (:) [New-TypeData], InvalidCastException
    + FullyQualifiedErrorId : System.InvalidCastException,UncommonSense.PowerShell.TypeData.Cmdlets.NewTypeDataCmdlet

```

In this case a 'Syntax Error' message is a better information.

**Comment by jhoek** [comment]
I see what you mean, but to me it's obvious that the root element Types should contain zero or more instances of Type, which can then contain NoteProperties and other members. In other words - Types expects instances of Type, and you're feeding it a NoteProperty. With that in mind, the existing error message appears to make sense? 

I'll try to find the time to add XML documentation to the module's cmdlets. Perhaps that could help inform users about the nature of input that is expected?

**Comment by LaurentDardenne** [comment]
> but to me it's obvious 

What is obvious for one is not for another :-)

> With that in mind, the existing error message appears to make sense?

I agree, but we are Developers, not simply users.
> In other words - Types expects instances of Type, and you're feeding it a NoteProperty.

Why do not use directly 'the other words' ?
Powershell DSL like Pester or PSake indicate syntax errors in this case

For the documentation Powershell help file can be contains this link : 
 https://msdn.microsoft.com/en-us/library/dd878306(v=vs.85).aspx

**Comment by jhoek** [comment]
I like the idea, but I don't have the time to fix this right now. I'd be more than happy to merge in a pull request, though! :-)
