### ISSUE TITLE
Improvement : Add Debug stream

### ISSUE THREAD

**Issue by LaurentDardenne** [jhoek/UncommonSense.PowerShell.TypeData#7]
Today I create dynamically the code of members, and i use Write-debug in my code :
```Powershell
 Write-Debug "`tWrite ScriptMethod '$($_.Name)'"
 Write-debug "`tscript: $SwitchScript"
 New-ScriptMethod -Name $_.Name -Script $SwitchScript

DEBUG:  Write ScriptMethod 'NotIn'
DEBUG:  script:
   switch ($args.Count) {
            1 { [Extensions]::NotIn($this,$args[0])}

            default { throw "The method 'NotIn' does not offer a signature containing $($args.Count) parameters." }
          }

```
This writing would be appreciated : 
```Powershell
New-ScriptMethod -Name $_.Name -Script $SwitchScript -Debug

DEBUG:  Write ScriptMethod 'NotIn'
DEBUG:  script:
   switch ($args.Count) {
            1 { [Extensions]::NotIn($this,$args[0])}

            default { throw "The method 'NotIn' does not offer a signature containing $($args.Count) parameters." }
          }
```
The cmdlet send the content of its parameters to the debug stream.

**Comment by jhoek** [comment]
I understand. Would this qualify as Debug output, or as Verbose output? 

You would lose the possibility to add the leading tab character that you appear to be adding manually in your code above, right?

**Comment by LaurentDardenne** [comment]
> Would this qualify as Debug output, or as Verbose output?

Debug Output, It is just for an issue.

> You would lose the possibility to add the leading tab character that you appear to be adding manually in your code above, right?

Yes, that's not embarassing.

**Comment by jhoek** [comment]
Have given it some more thought, and I don't think this adds the most value at this point. Let's come back to this feature request later.
